// web/src/components/FileConnection.svelte
<script>
	import { onMount } from 'svelte';
	import { endpoint } from '$lib/utils';

	let ptypes = [];
	onMount(async () => {
		const response = await fetch(endpoint(`connections/providers/types`));
		ptypes = await response.json();
		console.log(ptypes);
	});

	const fileFormats = [
		{ name: 'CSV', code: 'csv' },
		{ name: 'JSON', code: 'json' }
	];
	export let state;
</script>

<template lang="pug">
  .form-item
    label(for='file-provider') Provider
    select#file-provider(aria-label='provider')
      +each('ptypes as p')
        option(value='{p.code}' selected='{p.code === state?.provider}') {p.name}
  .form-item
    label(for='file-format') Format
    select#file-format(aria-label='file format')
      +each('fileFormats as ff')
        option(value='{ff.code}' selected='{ff.code === state?.format}') {ff.name}
</template>

// web/src/pages/connections/types/file/FileConnection.vue
<template lang="pug">
a-form-item(label='Provider', name='provider')
  a-select(v-model:value='state.provider')
    a-select-option(v-for='m in providerTypes', :value='m.code') {{ m.name }}
a-form-item(label='Format', name='format')
  a-select(v-model:value='state.format')
    a-select-option(value='csv') CSV
a-form-item(
  label='Path',
  name='path',
  :rules='[{ required: true, message: "Please enter file path", validator: validatePath }]'
)
  a-input(v-model:value='state.path')
</template>

<script setup>
import { defineProps, onBeforeMount, ref } from 'vue'
import { useStore } from 'vuex'

const providerTypes = ref([])
const store = useStore()

onBeforeMount(() => {
  store.dispatch('connections/getProviderTypes').then((types) => {
    providerTypes.value = types
  })
})

const validatePath = (rule, value) => {
  if (props.state.path.length === 0) {
    return Promise.reject(new Error('Please enter file path'))
  } else {
    return Promise.resolve()
  }
}

const props = defineProps({
  state: {
    type: Object,
    default: () => ({
      path: '',
      provider: 's3',
      format: 'csv'
    })
  }
})
</script>
