// web/src/components/MySQLConnection.svelte
<script>
	export let state = {};
</script>

<template lang="pug">
  .form-item
    label(for='host-name') Host
    input.mt-1(type='text' id="host-name" name='host' autocomplete='mysql-host-name' bind:value='{state.host}')

  .form-item
    label(for='port') Port
    input.mt-1(type='number' id="port" name='port' autocomplete='mysql-port' bind:value='{state.port}')

  .form-item
    label(for='database') Database
    input.mt-1(type='text' id="database" name='database' autocomplete='mysql-database' bind:value='{state.database}')

  .form-item
    label(for='username') Username
    input.mt-1(type='text' id="username" name='username' autocomplete='mysql-username' bind:value='{state.username}')

  .form-item
    label(for='password') Password
    input.mt-1(type='password' id="password" name='password' autocomplete='mysql-password' bind:value='{state.password}')

</template>

// web/src/pages/connections/types/mysql/MySQLConnection.vue
<template lang="pug">
a-form-item(label='Host', name='host', :rules='[{ required: true, validator: validateHost }]')
  a-input(v-model:value='state.host')
a-form-item(label='Port', name='port', :wrapper-col='{ span: 8 }')
  a-input-number(v-model:value='state.port', :min='0', :max='65535', style='width: 100%')
a-form-item(label='Database', name='database')
  a-input(v-model:value='state.database')
a-form-item(label='Username', name='username')
  a-input(v-model:value='state.username')
a-form-item(label='Password', name='password')
  a-input-password(v-model:value='state.password', autoComplete='off')
a-form-item(label='Params', name='params')
  a-input(v-model:value='state.params')
</template>

<script setup>
import { defineProps } from 'vue'

const validateHost = (rule) => {
  if (props.state.host.length === 0) {
    return Promise.reject(new Error(rule.message))
  } else {
    return Promise.resolve()
  }
}

const props = defineProps({
  state: {
    type: Object,
    default: () => ({
      host: '',
      port: 3306
    })
  }
})
</script>
